num1 = float(input('Informe o primeiro número: '))
num2 = float(input('Informe o segundo número: '))
num3 = float(input('Informe o terceiro número: '))
soma = (num1**2)+(num2**2)+(num3**2)
print('A soma do quadrado dos três valores é: ',soma)